# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: dev
    application:
        name: securitymultifactor
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false 